
//COPYRIGHT SEARCHAREA DATACENTER AND SEARCHAREA FRANCE, USA, RUSSIA and ITALIA
//SCRIPT BY SEARCHAREA FRANCE, POLOOHYEAH AND DRISS
//SEARCH AREA WEB SEARCH AND AREA MAPS USE WEBSEARCH SCRIPT 
//SCRIPT V2.0 AVEC FUSE.JS 


// Définition de la fonction openPage
function openPage() {
  // Récupération de la valeur de la barre de recherche
  var searchTerm = document.getElementById("search").value;

  // Définition des correspondances terme de recherche => fichier HTML
  var searchMappings = [
    { term: "gironde", file: "gironde.html" },
    { term: "incendie gironde", file: "gironde.html" },
    { term: "chat", file: "chat.html" },
    { term: "petit chat", file: "chat.html" },
    { term: "chat trop mignon", file: "chat.html" },
    { term: "twitter", file: "twitter.html" },
    { term: "twitter certification", file: "twitter.html" },
    { term: "obtenir la certification twitter", file: "twitter.html" },
    { term: "twitter web", file: "twitter.html" },
    { term: "PoloOhYeah", file: "poloohyeah.html" },
    { term: "poloohyeah", file: "poloohyeah.html" },
    { term: "polo oh yeah", file: "poloohyeah.html" },
    { term: "SNCF", file: "sncf.html" },
    { term: "sncf", file: "sncf.html" },
    { term: "SNCF Connect", file: "sncf.html" },
    { term: "sncf connect", file: "sncf.html" },
    { term: "horaires de train", file: "sncf.html" },
    { term: "rer d", file: "rerdsearch.html" },
    { term: "rer b", file: "sncf.html" },
    { term: "ratp", file: "sncf.html" },
    { term: "ratp greves", file: "sncf.html" },
    { term: "google", file: "google.html" },
    { term: "google chrome", file: "chrome.html" },
    { term: "navigateur chrome", file: "chrome.html" },
    { term: "installer chrome", file: "chrome.html" },
    { term: "crhome", file: "chrome.html" },
    { term: "prendre chrome", file: "chrome.html" },
    { term: "télécharger chrome", file: "chrome.html" },
    { term: "google application", file: "chrome.html" },
    { term: "transilien", file: "sncf.html" },
    { term: "train", file: "sncf.html" },
    { term: "transport ile de france", file: "sncf.html" },
    { term: "transport idf", file: "sncf.html" },
    { term: "tgv", file: "sncf.html" },
    { term: "ter", file: "sncf.html" },
    { term: "billet de train", file: "sncf.html" },
    { term: "train billet", file: "sncf.html" },
    { term: "ouigo", file: "sncf.html" },
    { term: "inoui", file: "sncf.html" },
    { term: "tgv inoui", file: "sncf.html" },
    { term: "apple", file: "apple.html" },
    { term: "téléphone apple", file: "apple.html" },
    { term: "iphone 14", file: "apple.html" },
    { term: "iphone 13", file: "apple.html" },
    { term: "iphone 12", file: "apple.html" },
    { term: "iphone 11", file: "apple.html" },
    { term: "airpods", file: "apple.html" },
    { term: "écouteurs apple", file: "apple.html" },
    { term: "casque apple", file: "apple.html" },
    { term: "wwdc apple", file: "apple.html" },
    { term: "ios 17", file: "apple.html" },
    { term: "ios 16", file: "apple.html" },
    { term: "ios jailbreak", file: "howtojailbreak.html" },
    { term: "jailbreak iphone", file: "howtojailbreak.html" },
    { term: "comment jailbreak son iphone", file: "howtojailbreak.html" },
    { term: "comment jailbreak iphone ios 16.5", file: "howtojailbreak.html" },
    { term: "comment jailbreak iphone ios 16.3", file: "howtojailbreak.html" },
    { term: "comment jailbreak iphone ios 16", file: "howtojailbreak.html" },
    { term: "how to jailbreak iphone", file: "howtojailbreak.html" },
    { term: "mac", file: "apple.html" },
    { term: "macintosh", file: "apple.html" },
    { term: "imac", file: "apple.html" },
    { term: "pc apple", file: "apple.html" },
    { term: "github", file: "github.html" },
    { term: "git", file: "github.html" },
    { term: "gith", file: "github.html" },
    { term: "télécharger github", file: "github.html" },
    { term: "github windows télécharger", file: "github.html" },
    { term: "android", file: "android.html" },
    { term: "téléphone android", file: "android.html" },
    { term: "google pixel 7a", file: "googlepixel.html" },
    { term: "google pixel 7", file: "googlepixel.html" },
    { term: "google pixel 6", file: "googlepixel.html" },
    { term: "google pixel", file: "googlepixel.html" },
    { term: "android 14", file: "android.html" },
    { term: "bitcoin", file: "bitcoin.html" },
    { term: "btc", file: "bitcoin.html" },
    { term: "cours du bitcoin", file: "bitcoin.html" },
    { term: "cours des cryptomonaie", file: "bitcoin.html" },
    { term: "crypto", file: "bitcoin.html" },
    { term: "cryptomonaie", file: "bitcoin.html" },
    { term: "lemonde", file: "lemonde.html" },
    { term: "journal le monde", file: "lemonde.html" },
    { term: "actualité le monde", file: "lemonde.html" },
    { term: "mufc", file: "mufc.html" },
    { term: "manchester united", file: "mufc.html" },
    { term: "m united", file: "mufc.html" },
    { term: "rmc sport", file: "rmcsport.html" },
    { term: "rmc", file: "rmcsport.html" },
    { term: "sport rmc", file: "rmcsport.html" },
    { term: "car glass", file: "carglass.html" },
    { term: "car glasse", file: "carglass.html" },
    { term: "glass car", file: "carglass.html" },
    { term: "parebrise cassé", file: "carglass.html" },
    { term: "Microsoft", file: "microsoft.html" },
    { term: "microsoft", file: "microsoft.html" },
    { term: "pc windows", file: "microsoft.html" },
    { term: "windows", file: "microsoft.html" },
    { term: "windows nt", file: "microsoft.html" },
    { term: "samsung", file: "samsung.html" },
    { term: "téléphone samsung", file: "samsung.html" },
    { term: "samsung a51", file: "samsung.html" },
    { term: "samsung zflip", file: "samsung.html" },
    { term: "téléphone samsung avec 5g", file: "samsung.html" },
    { term: "chien mignon", file: ".html" },
    { term: "chien", file: "chien.html" },
    { term: "chien de race", file: "chien.html" },
    { term: "chien shiba", file: "shiba.html" },
    { term: "shiba", file: "shiba.html" },
    { term: "shiba inu", file: "shiba.html" },
    { term: "chien squeezie", file: "shiba.html" },
    { term: "chien japon", file: "shiba.html" },
    { term: "instagram", file: "instagram.html" },
    { term: "insta", file: "instagram.html" },
    { term: "snapchat", file: "snapchat.html" },
    { term: "snap", file: "snapchat.html" },
    { term: "election 2022", file: "election2022.html" },
    { term: "éléction 2022", file: "election2022.html" },
    { term: "éléction président", file: "election2022.html" },
    { term: "éléction", file: "election2022.html" },
    { term: "éléction 2027", file: "election2022.html" },
    { term: "election 2027", file: "election2022.html" },
    { term: "USB", file: "usb.html" },
    { term: "usb", file: "usb.html" },
    { term: "universal serial bus", file: "usb.html" },
    { term: "péripherique usb", file: "usb.html" },
    { term: "usb mass storage", file: "usb.html" },
    { term: "disque dur externe", file: "usb.html" },
    { term: "geforce now", file: "geforce.html" },
    { term: "ge force now", file: "geforce.html" },
    { term: "geforce", file: "geforce.html" },
    { term: "nvidia geforce", file: "geforce.html" },
    { term: "geforce nvidia", file: "geforce.html" },
    { term: "fortnite", file: "fortnite.html" },
    { term: "fortnite battle royale", file: "fortnite.html" },
    { term: "fortnite a2f", file: "a2f.html" },
    { term: "minecraft", file: "minecraft.html" },
    { term: "minecraft", file: "minecraft.html" },
    { term: "minecraft legend", file: "minecraft.html" },
    { term: "minecraft java edition", file: "minecraft.html" },
    { term: "minecraft launcher", file: "minecraft.html" },
    { term: "minecraft bedrock", file: "minecraft.html" },
    { term: "mojang", file: "minecraft.html" },
    { term: "mojang studio", file: "minecraft.html" },
    { term: "youtube", file: "youtube.html" },
    { term: "you tube", file: "youtube.html" },
    { term: "Steam", file: "steam.html" },
    { term: "steam", file: "steam.html" },
    { term: "counter strike pc", file: "steam.html" },
    { term: "U2", file: "u2search.html" },
    { term: "u2", file: "u2search.html" },
    { term: "bono", file: "u2search.html" },
    { term: "Bono", file: "u2search.html" },
    { term: "the edge", file: "u2search.html" },
    { term: "comment activer a2f", file: "a2f.html" },
    { term: "activer a2f sur fortnite", file: "a2f.html" },
    { term: "guerre en ukraine", file: "guerreukraine.html" },
    { term: "guerre ukraine", file: "guerreukraine.html" },
    { term: "guerre russe en ukraine", file: "guerreukraine.html" },
    { term: "conflit russe ukraine", file: "guerreukraine.html" },
    { term: "conflit ukraine russe", file: "guerreukraine.html" },
    { term: "conflit russie ukraine", file: "guerreukraine.html" },
    { term: "guerre kiev", file: "guerreukraine.html" },
    { term: "barrage en ukraine explosion", file: "guerreukraine.html" },
    { term: "barrage en ukraine", file: "guerreukraine.html" },
    { term: "variole du singe", file: "singe.html" },
    { term: "singe maladie", file: "singe.html" },
    { term: "variole singe", file: "singe.html" },
    { term: "covid 19", file: "covid.html" },
    { term: "covid-19", file: "covid.html" },
    { term: "covid", file: "covid.html" },
    { term: "corona", file: "covid.html" },
    { term: "coronavirus", file: "covid.html" },
    { term: "test pcr", file: "covid.html" },
    { term: "test covid 19", file: "covid.html" },
    { term: "test covid", file: "covid.html" },
    { term: "test coronavirus", file: "covid.html" },
    { term: "vaccin covid", file: "covid.html" },
    { term: "vaccination covid", file: "covid.html" },
    { term: "ovh", file: "ovh.html" },
    { term: "ovh cloud", file: "ovh.html" },
    { term: "cloud ovh", file: "ovh.html" },
    { term: "incendie ovh", file: "ovh.html" },
    { term: "ovh incendie", file: "ovh.html" },
    { term: "aws", file: "aws.html" },
    { term: "amazon serveur aws", file: "aws.html" },
    { term: "amazon serveur", file: "aws.html" },
    { term: "serveur amazon aws", file: "aws.html" },
    { term: "serveur amazon", file: "aws.html" },
    { term: "gmail", file: "gmail.html" },
    { term: "google mail", file: "gmail.html" },
    { term: "mail google", file: "gmail.html" },
    { term: "mail de google", file: "gmail.html" },
    { term: "compte google", file: "gmail.html" },
    { term: "outlook", file: "outlook.html" },
    { term: "outlook mail", file: "outlook.html" },
    { term: "hotmail", file: "outlook.html" },
    { term: "mail outlook", file: "outlook.html" },
    { term: "mail microsoft", file: "outlook.html" },
    { term: "spotify", file: "spotify.html" },
    { term: "musique spotify", file: "spotify.html" },
    { term: "spotify musique", file: "spotify.html" },
    { term: "spotify android", file: "spotify.html" },
    { term: "spotify windows", file: "spotify.html" },
    { term: "sos", file: "sos.html" },
    { term: "appel d'urgence", file: "sos.html" },
    { term: "urgence absolue", file: "sos.html" },
    { term: "besoin d'aide", file: "sos.html" },
    { term: "urgence appel", file: "sos.html" },
    { term: "foot", file: "foot.html" },
    { term: "football", file: "foot.html" },
    { term: "foot sale", file: "foot.html" },
    { term: "foot en salle", file: "foot.html" },
    { term: "neymar", file: "foot.html" },
    { term: "messi", file: "foot.html" },
    { term: "psg", file: "foot.html" },
    { term: "pornhub", file: "pornhub.html" },
    { term: "porn hub", file: "pornhub.html" },
    { term: "porno gratuit", file: "pornhub.html" },
    { term: "pornzone", file: "pornzoneconfirme.html" },
    { term: "tukif", file: "pornhub.html" },
    { term: "wikipedia", file: "wiki.html" },
    { term: "wiki", file: "wiki.html" },
    { term: "encyclopédie", file: "wiki.html" },
    { term: "wikipedia français", file: "wiki.html" },
    { term: "coupe du monde de foot", file: "coupedumonde.html" },
    { term: "coupe de monde de football", file: "coupedumonde.html" },
    { term: "coupe du monde", file: "coupedumonde.html" },
    { term: "coupe du monde qatar", file: "coupedumonde.html" },
    { term: "foot qatar", file: "coupedumonde.html" },
    { term: "coupe foot", file: "coupedumonde.html" },
    { term: "foot coupe", file: "coupedumonde.html" },
    { term: "gp explorer", file: "gpexplorer.html" },
    { term: "GP Explorer", file: "gpexplorer.html" },
    { term: "gp explorer 2", file: "gpexplorer.html" },
    { term: "GP Explorer 2", file: "gpexplorer.html" },
    { term: "gp explorer squeezie", file: "gpexplorer.html" },
    { term: "squeezie gp explorer", file: "gpexplorer.html" },
    { term: "gp squeezie", file: "gpexplorer.html" },
    { term: "squeezie gp", file: "gpexplorer.html" },
    { term: "BUS R2", file: "busr2.html" },
    { term: "bus r2", file: "busr2.html" },
    { term: "r2 bus", file: "busr2.html" },
    { term: "keolis bus r2", file: "busr2.html" },
    { term: "keolis r2", file: "busr2.html" },
    { term: "horaires bus r2", file: "busr2.html" },
    { term: "bus r2 horaire", file: "busr2.html" },
    { term: "bouygues telecom", file: "bouygues.html" },
    { term: "bouygues", file: "bouygues.html" },
    { term: "bouygues telecom forfait", file: "bouygues.html" },
    { term: "SFR", file: "sfr.html" },
    { term: "sfr", file: "sfr.html" },
    { term: "sfr forfait", file: "sfr.html" },
    { term: "orange", file: "orange.html" },
    { term: "orange forfait", file: "orange.html" },
    { term: "orange livebox", file: "orange.html" },
    { term: "free", file: "free.html" },
    { term: "Free", file: "free.html" },
    { term: "free forfait", file: "free.html" },
    { term: "free freebox", file: "free.html" },
    { term: "lycee de la tourelle", file: "tourelle.html" },
    { term: "lycee la tourelle", file: "tourelle.html" },
    { term: "lycee maryse conde", file: "tourelle.html" },
    { term: "lycee sarcelles", file: "tourelle.html" },
    { term: "amazon", file: "amazon.html" },
    { term: "AMAZON", file: "amazon.html" },
    { term: "france info", file: "franceinfo.html" },
    { term: "franceinfo", file: "franceinfo.html" },
    { term: "info france", file: "franceinfo.html" },
    { term: "LCI", file: "lci.html" },
    { term: "lci", file: "lci.html" },
    { term: "lci actualités", file: "lci.html" },
    { term: "actualités lci", file: "lci.html" },
    { term: "Intel", file: "intel.html" },
    { term: "intel", file: "intel.html" },
    { term: "Intel core i5", file: "intel.html" },
    { term: "intel core i3", file: "intel.html" },
    { term: "intel xeon", file: "intel.html" },
    { term: "intel pentium", file: "intel.html" },
    { term: "intel atom", file: "intel.html" },
    { term: "intel core 2 duo", file: "intel.html" },
    { term: "processeur intel", file: "intel.html" },
    { term: "intel processeur", file: "intel.html" },
    { term: "xeon", file: "intel.html" },
    { term: "Netflix", file: "netflix.html" },
    { term: "netflix", file: "netflix.html" },
    { term: "serie netflix", file: "netflix.html" },
    { term: "film netflix", file: "netflix.html" },
    { term: "russie", file: "russie.html" },
    { term: "russe", file: "russie.html" },
    { term: "russia", file: "russie.html" },
    { term: "russian", file: "russie.html" },
    { term: "russie pays", file: "russie.html" },
    { term: "président de la russie", file: "russie.html" },
    { term: "qui est le président de la russie", file: "russie.html" },
    { term: "france", file: "france.html" },
    { term: "français", file: "france.html" },
    { term: "qui est le président de la france", file: "france.html" },
    { term: "france président", file: "france.html" },
    { term: "paris2024", file: "paris2024.html" },
    { term: "paris 2024", file: "paris2024.html" },
    { term: "jo de paris", file: "paris2024.html" },
    { term: "jeux olympique de paris", file: "paris2024.html" },
    { term: "maroc", file: "maroc.html" },
    { term: "Maroc", file: "maroc.html" },
    { term: "président maroc", file: "maroc.html" },
    { term: "qui est le président du maroc", file: "maroc.html" },
    { term: "maroc equipe de foot", file: "maroc.html" },
    { term: "maroc coupe du monde", file: "maroc.html" },
    { term: "europe", file: "europe.html" },
    { term: "union européenne", file: "europe.html" },
    { term: "banque europe", file: "europe.html" },
    { term: "banque centrale europe", file: "europe.html" },
    { term: "etats unis", file: "usa.html" },
    { term: "Etats-Unis", file: "usa.html" },
    { term: "USA", file: "usa.html" },
    { term: "usa", file: "usa.html" },
    { term: "etats unis coupe du monde", file: "usa.html" },
    { term: "Pokémon", file: "pokemon.html" },
    { term: "pokemon", file: "pokemon.html" },
    { term: "Paris", file: "paris.html" },
    { term: "paris", file: "paris.html" },
    { term: "transport paris", file: "paristransport.html" },
    { term: "paris rer d", file: "paristransport.html" },
    { term: "paris rer b", file: "paristransport.html" },
    { term: "paris metro", file: "paristransport.html" },
    { term: "paris gare du nord", file: "paristransport.html" },
    { term: "paris gare de lyon", file: "paristransport.html" },
    { term: "Fosses", file: "fosses.html" },
    { term: "fosses", file: "fosses.html" },
    { term: "fosses college", file: "fosses.html" },
    { term: "fosses lycee", file: "fosses.html" },
    { term: "lycée fosses", file: "fosses.html" },
    { term: "college fosses", file: "fosses.html" },
    { term: "fosses rer d", file: "fosses.html" },
    { term: "mairie de fosses", file: "fosses.html" },
    { term: "Sarcelles", file: "sarcelles.html" },
    { term: "sarcelles", file: "sarcelles.html" },
    { term: "sarcelles village", file: "sarcelles.html" },
    { term: "cinema sarcelles", file: "sarcelles.html" },
    { term: "cgr sarcelles", file: "sarcelles.html" },
    { term: "sarcelles my place", file: "sarcelles.html" },
    { term: "my place sarcelles", file: "sarcelles.html" },
    { term: "lycée sarcelles", file: "sarcelles.html" },
    { term: "goussainville", file: "goussainville.html" },
    { term: "Goussainville", file: "goussainville.html" },
    { term: "college goussainville", file: "goussainville.html" },
    { term: "lycee goussainville", file: "goussainville.html" },
    { term: "goussainville rer d", file: "goussainville.html" },
    { term: "goussainville village", file: "goussainville.html" },
    { term: "Villiers-le-Bel", file: "villiers.html" },
    { term: "Villiers le Bel", file: "villiers.html" },
    { term: "villiers le bel", file: "villiers.html" },
    { term: "gare de villiers rer d", file: "villiers.html" },
    { term: "gare de villiers", file: "villiers.html" },
    { term: "rer d villiers le bel", file: "villiers.html" },
    { term: "rer villiers le bel", file: "villiers.html" },
    { term: "bus 269", file: "bus269.html" },
    { term: "BUS 269", file: "bus269.html" },
    { term: "bus 269 sarcelles", file: "bus269.html" },
    { term: "bus 269 attainville", file: "bus269.html" },
    { term: "bus 269 horaires", file: "bus269.html" },
    { term: "horaires bus 269", file: "bus269.html" },
    { term: "RER D", file: "rerdsearch.html" },
    { term: "rer d", file: "rerdsearch.html" },
    { term: "Rer d", file: "rerdsearch.html" },
    { term: "Rer D", file: "rerdsearch.html" },
    { term: "Transilien D", file: "rerdsearch.html" },
    { term: "ligne d du rer", file: "rerdsearch.html" },
    { term: "ligne d sncf", file: "rerdsearch.html" },
    { term: "horaires rer d", file: "rerdsearch.html" },
    { term: "rer d horaires", file: "rerdsearch.html" },
    { term: "greves rer d", file: "rerdsearch.html" },
    { term: "rer d greves", file: "rerdsearch.html" },
    { term: "PS4", file: "playstation.html" },
    { term: "ps4", file: "playstation.html" },
    { term: "Ps4", file: "playstation.html" },
    { term: "play station 4", file: "playstation.html" },
    { term: "sony ps4", file: "playstation.html" },
    { term: "PS5", file: "playstation.html" },
    { term: "ps5", file: "playstation.html" },
    { term: "Ps5", file: "playstation.html" },
    { term: "play station 5", file: "playstation.html" },
    { term: "sony ps5", file: "playstation.html" },
    { term: "FIFA 23", file: "fifa23.html" },
    { term: "FIFA", file: "fifa23.html" },
    { term: "fifa 23", file: "fifa23.html" },
    { term: "fifa ", file: "fifa23.html" },
    { term: "jeux fifa 23", file: "fifa23.html" },
    { term: "Listenbourg", file: "listenbourg.html" },
    { term: "listenbourg", file: "listenbourg.html" },
    { term: "Gusto Pizza", file: "gustopizza.html" },
    { term: "gusto pizza", file: "gustopizza.html" },
    { term: "gustopizza", file: "gustopizza.html" },
    { term: "pizza fosses", file: "gustopizza.html" },
    { term: "BlackView", file: "blackview.html" },
    { term: "Black View", file: "blackview.html" },
    { term: "black view", file: "blackview.html" },
    { term: "blackview", file: "blackview.html" },
    { term: "McDonald's", file: "mcdo.html" },
    { term: "McDo", file: "mcdo.html" },
    { term: "mcdo", file: "mcdo.html" },
    { term: "mcdonalds", file: "mcdo.html" },
    { term: "mcdo +", file: "mcdo.html" },
    { term: "Samsung Galaxy", file: "samsung.html" },
    { term: "samsung galaxy", file: "samsung.html" },
    { term: "téléphone galaxy samsung", file: "samsung.html" },
    { term: "téléphone galaxy", file: "samsung.html" },
    { term: "calculatrice", file: "calculatricesearch.html" },
    { term: "calcul", file: "calculatricesearch.html" },
    { term: "calculette", file: "calculatricesearch.html" },
    { term: "DIX", file: "dix.html" },
    { term: "dix", file: "dix.html" },
    { term: "10", file: "dix.html" },
    { term: "voiture", file: "voiture.html" },
    { term: "voiture renault", file: "voiture.html" },
    { term: "voiture peugeot", file: "voiture.html" },
    { term: "citroen voiture", file: "voiture.html" },
    { term: "peugeot ocasion", file: "voiture.html" },
    { term: "peugeot 206 cc", file: "voiture.html" },
    { term: "renault", file: "voiture.html" },
    { term: "bandana", file: "bandana.html" },
    { term: "Air Force 1", file: "airforce1.html" },
    { term: "air force", file: "airforce1.html" },
    { term: "air force 1", file: "airforce1.html" },
    { term: "nike air force", file: "airforce1.html" },
    { term: "air force 1 nike", file: "airforce1.html" },
    { term: "nike", file: "airforce1.html" },
    { term: "nike air", file: "airforce1.html" },
    { term: "radiateur", file: "radiateur.html" },
    { term: "chauffage", file: "radiateur.html" },
    { term: "banderole", file: "banderole.html" },
    { term: "visage", file: "visage.html" },
    { term: "porte", file: "porte.html" },
    { term: "porte automatique", file: "porte.html" },
    { term: "porte coulissante", file: "porte.html" },
    { term: "porte ikea", file: "porte.html" },
    { term: "ikea porte", file: "porte.html" },
    { term: "Chien", file: "chien.html" },
    { term: "chien", file: "chien.html" },
    { term: "chien domestique", file: "chien.html" },
    { term: "chien absolument trop mignon", file: "chien.html" },
    { term: "chien de race rare", file: "chien.html" },
    { term: "chien batard", file: "chien.html" },
    { term: "Humain", file: "humain.html" },
    { term: "humain", file: "humain.html" },
    { term: "corps humain", file: "humain.html" },
    { term: "cargo", file: "cargo.html" },
    { term: "pentalon cargo", file: "cargo.html" },
    { term: "cargo pentalon", file: "cargo.html" },
    { term: "cargolux", file: "cargo.html" },
    { term: "cargolux airlines", file: "cargo.html" },
    { term: "cargo lux", file: "cargo.html" },
    { term: "mediatheque", file: "mediatheque.html" },
    { term: "médiathèque", file: "mediatheque.html" },
    { term: "bibliotheque", file: "mediatheque.html" },
    { term: "veste", file: "veste.html" },
    { term: "Veste", file: "veste.html" },
    { term: "traduction", file: "traduction.html" },
    { term: "translate", file: "traduction.html" },
    { term: "google traduction", file: "traduction.html" },
    { term: "google translate", file: "traduction.html" },
    { term: "traduction français anglais", file: "traduction.html" },
    { term: "traduction anglais français", file: "traduction.html" },
    { term: "Lunette", file: "lunette.html" },
    { term: "Lunettes", file: "lunette.html" },
    { term: "lunettes de vue", file: "lunette.html" },
    { term: "lunette de vue", file: "lunette.html" },
    { term: "lunette de soleil", file: "lunette.html" },
    { term: "téléphone", file: "telephone.html" },
    { term: "téléphonie ip", file: "telephone.html" },
    { term: "téléphone pas cher", file: "telephone.html" },
    { term: "téléphone amazon", file: "telephone.html" },
    { term: "téléphone reconditionné", file: "telephone.html" },
    { term: "sac", file: "sac.html" },
    { term: "SAC", file: "sac.html" },
    { term: "Sac", file: "sac.html" },
    { term: "Jogging", file: "jogging.html" },
    { term: "jogging", file: "jogging.html" },
    { term: "survetement", file: "jogging.html" },
    { term: "Horloge", file: "horloge.html" },
    { term: "horloge", file: "horloge.html" },
    { term: "sodomie", file: "sodomie.html" },
    { term: "Sodomie", file: "sodomie.html" },
    { term: "Sexe", file: "sexe.html" },
    { term: "sexe", file: "sexe.html" },
    { term: "sex", file: "sexe.html" },
    { term: "SEXE", file: "sexe.html" },
    { term: "team rocket", file: "teamrocket.html" },
    { term: "Team Rocket", file: "teamrocket.html" },
    { term: "team rocket pokemon", file: "teamrocket.html" },
    { term: "team rocket hentai", file: "teamrockethentai.html" },
    { term: "Team Rocket hentai", file: "teamrockethentai.html" },
    { term: "team rocket pokemon hentai", file: "teamrockethentai.html" },
    { term: "Escalier", file: "escalier.html" },
    { term: "escalier", file: "escalier.html" },
    { term: "masque", file: "masque.html" },
    { term: "Masque", file: "masque.html" },
    { term: "PayPal", file: "paypal.html" },
    { term: "paypal", file: "paypal.html" },
    { term: "pay pal", file: "paypal.html" },
    { term: "Ecouteur", file: "ecouteur.html" },
    { term: "écouteur", file: "ecouteur.html" },
    { term: "écouteur sans fil", file: "ecouteur.html" },
    { term: "écouteur filaire", file: "ecouteur.html" },
    { term: "casque filaire", file: "ecouteur.html" },
    { term: "casque sans fil", file: "ecouteur.html" },
    { term: "Booba", file: "booba.html" },
    { term: "booba", file: "booba.html" },
    { term: "HP", file: "hp.html" },
    { term: "hp", file: "hp.html" },
    { term: "Asus", file: "asus.html" },
    { term: "asus", file: "asus.html" },
    { term: "pc portable asus", file: "asus.html" },
    { term: "asus rog", file: "asus.html" },
    { term: "asus zen book", file: "asus.html" },
    { term: "pc gaming asus", file: "asus.html" },
    { term: "Alcatel", file: "alcatel.html" },
    { term: "alcatel", file: "alcatel.html" },
    { term: "téléphone alcatel", file: "alcatel.html" },
    { term: "alcatel téléphone", file: "alcatel.html" },
    { term: "batterie", file: "batterie.html" },
    { term: "Batterie", file: "batterie.html" },
    { term: "batterie au lithium", file: "batterie.html" },
    { term: "batterie lithium", file: "batterie.html" },
    { term: "Ecran", file: "ecran.html" },
    { term: "écran", file: "ecran.html" },
    { term: "ecran", file: "ecran.html" },
    { term: "ecran de pc gaming", file: "ecran.html" },
    { term: "ecran pc", file: "ecran.html" },
    { term: "ecran d'ordinateur", file: "ecran.html" },
    { term: "ecran 144 hz", file: "ecran.html" },
    { term: "tournevis", file: "tournevis.html" },
    { term: "tourne vis", file: "tournevis.html" },
    { term: "vis", file: "tournevis.html" },
    { term: "vis torx", file: "tournevis.html" },
    { term: "facebook", file: "facebook.html" },
    { term: "réseau facebook", file: "facebook.html" },
    { term: "facebook inscription", file: "facebook.html" },
    { term: "Hitler", file: "hitler.html" },
    { term: "adolf hitler", file: "hitler.html" },
    { term: "hitler adolf", file: "hitler.html" },
    { term: "hitler nazisme", file: "hitler.html" },
    { term: "Hunter X Hunter", file: "hunterxhunter.html" },
    { term: "hunter x hunter", file: "hunterxhunter.html" },
    { term: "Hunter x Hunter", file: "hunterxhunter.html" },
    { term: "hunter hunter", file: "hunterxhunter.html" },
    { term: "hunter x hunter nouvelle saison", file: "hunterxhunter.html" },
    { term: "hunter x hunter streaming", file: "hunterxhunter.html" },
    { term: "créer un site internet", file: "creewebsite.html" },
    { term: "créez un site internet", file: "creewebsite.html" },
    { term: "créer un site web", file: "creewebsite.html" },
    { term: "créez un site web", file: "creewebsite.html" },
    { term: "créer un site", file: "creewebsite.html" },
    { term: "créez un site", file: "creewebsite.html" },
    { term: "créer un site en html et css", file: "creewebsite.html" },
    { term: "créez un site en html et css", file: "creewebsite.html" },
    { term: "créer un site web gratuitement", file: "creewebsite.html" },
    { term: "créez un site web gratuitement", file: "creewebsite.html" },
    { term: "créer site internet html css", file: "creewebsite.html" },
    { term: "développé un site internet", file: "creewebsite.html" },
    { term: "Pourquoi il y a la guerre en ukraine", file: "guerreukraine.html" },
    { term: "pourquoi il y a la guerre en ukraine ?", file: "guerreukraine.html" },
    { term: "installer github", file: "github.html" },
    { term: "installer github sur windows", file: "github.html" },
    { term: "github pour windows", file: "github.html" },
    { term: "github android", file: "github.html" },
    { term: "prendre github", file: "github.html" },
    { term: "fleurs", file: "fleurs.html" },
    { term: "fleurs pas cher", file: "fleurs.html" },
    { term: "fleuriste", file: "fleurs.html" },
    { term: "fleurs paris", file: "fleurs.html" },
    { term: "adresse fleuriste", file: "fleurs.html" },
    { term: "fleurs rose", file: "fleurs.html" },
    { term: "magasin de fleurs", file: "fleurs.html" },
    { term: "fleurs jolie", file: "fleurs.html" },
    { term: "X", file: "twitter.html" },
    { term: "X twitter", file: "twitter.html" },
    { term: "Jasminade de grasse", file: "grassejasmin.html" },
    { term: "grasse jasmin", file: "grassejasmin.html" },
    { term: "grasse", file: "grassejasmin.html" },
    { term: "jasmin grasse", file: "grassejasmin.html" },
    { term: "SOS", file: "sos.html" },
    { term: "SOS d'urgence", file: "sos.html" },
    { term: "urgence", file: "sos.html" },
    { term: "j'ai besoin d'aide", file: "sos.html" },
    { term: "russie", file: "russie.html" },
    { term: "russe", file: "russie.html" },
    { term: "russkov", file: "russie.html" },
    { term: "JO de paris", file: "paris2024.html" },
    { term: "parsi jo", file: "paris2024.html" },
    { term: "jo 2024", file: "paris2024.html" },
    { term: "paris 2024", file: "paris2024.html" },
    { term: "Le monde", file: "lemonde.html" },
    { term: "le monde", file: "lemonde.html" },
    { term: "le monde journal", file: "lemonde.html" },
    { term: "RER dans paris", file: "paristransport.html" },
    { term: "paris transport en commun", file: "paristransport.html" },
    { term: "transport dans paris", file: "paristransport.html" },
    { term: "metro paris", file: "paristransport.html" },
    { term: "Météo", file: "meteo.html" },
    { term: "Meteo", file: "meteo.html" },
    { term: "meteo paris", file: "meteo.html" },
    { term: "meteo lille", file: "meteo.html" },
    { term: "meteo marseille", file: "meteo.html" },
    { term: "meteo cannes", file: "meteo.html" },
    { term: "meteo arcachon", file: "meteo.html" },
    { term: "croix rouge française", file: "croixrouge.html" },
    { term: "croix rouge", file: "croixrouge.html" },
    { term: "c'est quoi la croix rouge", file: "croixrouge.html" },
    { term: "ambulance croix rouge", file: "croixrouge.html" },
    { term: "association croix rouge", file: "croixrouge.html" },
    { term: "watchpeopledie", file: "watchpeopledie.html" },
    { term: "watch people die", file: "watchpeopledie.html" },
    { term: "regardez les gens mourir", file: "watchpeopledie.html" },
    { term: "people die watch", file: "watchpeopledie.html" },
    { term: "c'est quoi un ornithorynque", file: "ornithorynque.html" },
    { term: "ornithorynque", file: "ornithorynque.html" },
    { term: "acheter ornithorynque", file: "ornithorynque.html" },
    { term: "elevage ornithorynque", file: "ornithorynque.html" },
    { term: "ornithorynque prix", file: "ornithorynque.html" },
    { term: "ornithorynque def", file: "ornithorynque.html" },
    { term: "python", file: "python.html" },
    { term: "python télécharger", file: "python.html" },
    { term: "télécharger python", file: "python.html" },
    { term: "Voicemeeter", file: "voicemeeter.html" },
    { term: "télécharger voicemeeter", file: "voicemeeter.html" },
    { term: "voicemeeter aide", file: "voicemeeter.html" },
    { term: "Office 365", file: "office365.html" },
    { term: "télécharger office", file: "office365.html" },
    { term: "word telecharger", file: "office365.html" },
    { term: "microsoft word", file: "office365.html" },
    { term: "arabe", file: "arabe.html" },
    { term: "langue arabe", file: "arabe.html" },
    { term: "apprendre l'arabe", file: "arabe.html" },
    { term: "arabie saoudite", file: "arabe.html" },
    { term: "arbre", file: "arbre.html" },
    { term: "plantation arbre", file: "arbre.html" },
    { term: "acheter arbre", file: "arbre.html" },
    { term: "pommier", file: "arbre.html" },
    { term: "Toyota", file: "toyota.html" },
    { term: "voiture toyota", file: "toyota.html" },
    { term: "toyota hybride", file: "toyota.html" },
    { term: "manga", file: "manga.html" },
    { term: "lire manga en ligne", file: "manga.html" },
    { term: "acheter manga", file: "manga.html" },
    { term: "ludothèque", file: "ludotheque.html" },
    { term: "bibliothèque", file: "ludotheque.html" },
    { term: "cdi college", file: "ludotheque.html" },
    { term: "assiete ikea", file: "assiete.html" },
    { term: "acheter assiete", file: "assiete.html" },
    { term: "vaiselles", file: "assiete.html" },
    { term: "fossiles en france", file: "fossiles.html" },
    { term: "fossiles", file: "fossiles.html" },
    { term: "turitel", file: "fossiles.html" },
    { term: "Lenovo", file: "lenovo.html" },
    { term: "pc lenovo", file: "lenovo.html" },
    { term: "ordinateur lenovo", file: "lenovo.html" },
    { term: "lutti", file: "lutti.html" },
    { term: "bonbon lutti", file: "lutti.html" },
    { term: "Inuse", file: "inuse.html" },
    { term: "entreprise inuse", file: "inuse.html" },
    { term: "ent ile de france", file: "lyceeiledefrance.html" },
    { term: "lycee ile de france", file: "lyceeiledefrance.html" },
    { term: "lycee 95", file: "lyceeiledefrance.html" },
    { term: "portefeuille", file: "portefeuille.html" },
    { term: "portefeuille acheter", file: "portefeuille.html" },
    { term: "petit portefeuille", file: "portefeuille.html" },
    { term: "Parcoursup", file: "parcoursup.html" },
    { term: "inscription parcoursup", file: "parcoursup.html" },
    { term: "voeux parcoursup", file: "parcoursup.html" },
    { term: "drapeau", file: "drapeau.html" },
    { term: "drapeau pays", file: "drapeau.html" },
    { term: "drapeau du monde", file: "drapeau.html" },
    { term: "etiquette", file: "etiquette.html" },
    { term: "acheter etiquette", file: "etiquette.html" },
    { term: "etiquette collante", file: "etiquette.html" },
    { term: "peugeot", file: "peugeot.html" },
    { term: "voiture peugeot", file: "peugeot.html" },
    { term: "peugeot hybride", file: "peugeot.html" },
    { term: "renault", file: "renault.html" },
    { term: "voiture renault", file: "renault.html" },
    { term: "renault hybride", file: "renault.html" },
    { term: "roue", file: "roue.html" },
    { term: "pneu", file: "roue.html" },
    { term: "roue de velo", file: "roue.html" },
    { term: "armoire", file: "armoire.html" },
    { term: "armoire ikea", file: "armoire.html" },
    { term: "castorama armoire", file: "armoire.html" },
    { term: "montcuq", file: "montcuq.html" },
    { term: "tourisme montcuq", file: "montcuq.html" },
    { term: "ville de montcuq", file: "montcuq.html" },
    { term: "negro", file: "negro.html" },
    { term: "histoire cours 1800", file: "negro.html" },
    { term: "noir", file: "negro.html" },
    { term: "brico depot", file: "bricodepot.html" },
    { term: "planche brico depot", file: "bricodepot.html" },
    { term: "promos brico depot", file: "bricodepot.html" },
    { term: "ampoule led", file: "ampoule.html" },
    { term: "ampoule", file: "ampoule.html" },
    { term: "eclairage", file: "ampoule.html" },
    { term: "serrurier", file: "serrurier.html" },
    { term: "serrurier a paris", file: "serrurier.html" },
    { term: "serrure bloqué", file: "serrurier.html" },
    { term: "dragon ball", file: "dragonball.html" },
    { term: "fragon ball super", file: "dragonball.html" },
    { term: "manga dragon ball", file: "dragonball.html" },
    { term: "coquillage conque", file: "conque.html" },
    { term: "conque", file: "conque.html" },
    { term: "conque wiki", file: "conque.html" },
    { term: "jul", file: "jul.html" },
    { term: "rappeur jul", file: "jul.html" },
    { term: "le j c'est le s", file: "jul.html" },
    { term: "jul marseille", file: "jul.html" },
    { term: "gimp", file: "gimp.html" },
    { term: "gimp logiciel", file: "gimp.html" },
    { term: "logiciel gimp", file: "gimp.html" },
    { term: "montage gimp", file: "gimp.html" },
    { term: "télécharger gimp", file: "gimp.html" },
    { term: "snk", file: "snk.html" },
    { term: "attaque des titans", file: "snk.html" },
    { term: "snk fin", file: "snk.html" },
    { term: "regarder snk gratuit", file: "snk.html" },
    { term: "counter strike", file: "counterstrike.html" },
    { term: "télécharger counter strike", file: "counterstrike.html" },
    { term: "csgo", file: "counterstrike.html" },
    { term: "counter strike 2", file: "counterstrike.html" },
    { term: "steam counter strike", file: "counterstrike.html" },
    { term: "carte graphique", file: "cartegraphique.html" },
    { term: "carte graphique nvidia", file: "cartegraphique.html" },
    { term: "carte graphique amd", file: "cartegraphique.html" },
    { term: "carte graphique intel", file: "cartegraphique.html" },
    { term: "carte graphique pas cher", file: "cartegraphique.html" },
    { term: "google earth", file: "googleearth.html" },
    { term: "télécharger google earth", file: "googleearth.html" },
    { term: "google earth gratuit", file: "googleearth.html" },
    { term: "putty", file: "putty.html" },
    { term: "putty serial", file: "putty.html" },
    { term: "télécharger putty", file: "putty.html" },
    { term: "eminem concert", file: "eminem.html" },
    { term: "eminem fortnite", file: "eminem.html" },
    { term: "eminem evenement", file: "eminem.html" },
    { term: "eminem spotify", file: "eminem.html" },
    { term: "eminem", file: "eminem.html" },
    { term: "travis scott fortnite", file: "travisscott.html" },
    { term: "travis scott concert", file: "travisscott.html" },
    { term: "travis scott evenement", file: "travisscott.html" },
    { term: "travis scott spotify", file: "travisscott.html" },
    { term: "travis scott", file: "travisscott.html" },
    { term: "acer", file: "acer.html" },
    { term: "pc acer", file: "acer.html" },
    { term: "acer pc gaming", file: "acer.html" },
    { term: "acer pc pas cher", file: "acer.html" },
    { term: "acer aspire", file: "acer.html" },
    { term: "rer b", file: "rerb.html" },
    { term: "plan rer b", file: "rerb.html" },
    { term: "rer b paris", file: "rerb.html" },
    { term: "paris rer b", file: "rerb.html" },
    { term: "chatelet rer b", file: "rerb.html" },
    { term: "rer c", file: "rerc.html" },
    { term: "plan rer c", file: "rerc.html" },
    { term: "rer c paris", file: "rerc.html" },
    { term: "paris rer c", file: "rerc.html" },
    { term: "chatelet rer c", file: "rerc.html" },
    { term: "tour eiffel", file: "toureiffel.html" },
    { term: "tour eiffel prix", file: "toureiffel.html" },
    { term: "tour eiffel paris", file: "toureiffel.html" },
    { term: "tour eiffel itinéraire", file: "toureiffel.html" },
    { term: "Auchan", file: "auchan.html" },
    { term: "auchan drive", file: "auchan.html" },
    { term: "magasin auchan", file: "auchan.html" },
    { term: "brico depot", file: "bricodepot.html" },
    { term: "magasin bricolage", file: "bricodepot.html" },
    { term: "brico depot pas loin", file: "bricodepot.html" },
    { term: "fossiles", file: "fossiles.html" },
    { term: "fossiles bartonien", file: "fossiles.html" },
    { term: "ou trouver des fossiles", file: "fossiles.html" },
    { term: "studio ghibli", file: "ghibli.html" },
    { term: "ghibli", file: "ghibli.html" },
    { term: "film ghibli", file: "ghibli.html" },
    { term: "heppner", file: "heppner.html" },
    { term: "entreprise heppner", file: "heppner.html" },
    { term: "heppner logistique", file: "heppner.html" },
    { term: "jeux", file: "jeux.html" },
    { term: "jeux gratuit", file: "jeux.html" },
    { term: "jeux en ligne", file: "jeux.html" },
    { term: "panalpina", file: "panalpina.html" },
    { term: "panalpina dsv", file: "panalpina.html" },
    { term: "panalpina rachat", file: "panalpina.html" },
    { term: "portemonnaie", file: "portemonnaie.html" },
    { term: "portemonnaie pas cher", file: "portemonnaie.html" },
    { term: "portemonnaie cuire", file: "portemonnaie.html" },
    { term: "redmi", file: "redmi.html" },
    { term: "téléphone redmi", file: "redmi.html" },
    { term: "xiamoi", file: "redmi.html" },
    { term: "samsung", file: "samsung.html" },
    { term: "téléphone samsung", file: "samsung.html" },
    { term: "samsung s24 ultra", file: "samsung.html" },
    { term: "samsung galaxy", file: "samsung.html" },
    { term: "samsung s24", file: "samsung.html" },
    { term: "donne moi un itinéraire pour aller a paris depuis l'aeroport cdg", file: "gotoparisviaairportcdg.html" },
    { term: "samsung s21", file: "samsung.html" },
    { term: "entreprise 3m", file: "3m.html" },
    { term: "3m", file: "3m.html" },
    { term: "scotch 3m", file: "3m.html" },
    { term: "affichage", file: "affiche.html" },
    { term: "affiche", file: "affiche.html" },
    { term: "prix d'une affiche", file: "affiche.html" },
    { term: "profuit ajax", file: "ajax.html" },
    { term: "ajax", file: "ajax.html" },
    { term: "ajax asterdam", file: "ajax.html" },
    { term: "animé sama", file: "animesama.html" },
    { term: "anime sama", file: "animesama.html" },
    { term: "regarder animé gratuit", file: "animesama.html" },
    { term: "bluelock", file: "bluelock.html" },
    { term: "bluelock animé", file: "bluelock.html" },
    { term: "bluelock manga", file: "bluelock.html" },
    { term: "magasin casino", file: "casino.html" },
    { term: "casino", file: "casino.html" },
    { term: "casino en ligne", file: "casino.html" },
    { term: "cooler master", file: "coolermaster.html" },
    { term: "boitier cooler master", file: "coolermaster.html" },
    { term: "water colling cooler master", file: "coolermaster.html" },
    { term: "crunchyroll", file: "crunchyroll.html" },
    { term: "crunchyroll abonnement", file: "crunchyroll.html" },
    { term: "crunchyroll alternative", file: "animesama.html" },
    { term: "disney+", file: "disney+.html" },
    { term: "disney+ abonnement", file: "disney+.html" },
    { term: "streaming disney+", file: "disney+.html" },
    { term: "ebay", file: "ebay.html" },
    { term: "site marchand ebay", file: "ebay.html" },
    { term: "ebay promotion", file: "ebay.html" },
    { term: "fuzetea", file: "fuzetea.html" },
    { term: "boisson fuzetea", file: "fuzetea.html" },
    { term: "fuzetea prix", file: "fuzetea.html" },
    { term: "gay", file: "gay.html" },
    { term: "homosexuel", file: "gay.html" },
    { term: "couple gay", file: "gay.html" },
    { term: "ghibli", file: "ghibli.html" },
    { term: "studio ghibli", file: "ghibli.html" },
    { term: "le chateau ambulant", file: "ghibli.html" },
    { term: "gopro hero", file: "gopro.html" },
    { term: "gopro", file: "gopro.html" },
    { term: "prix gopro", file: "gopro.html" },
    { term: "gore", file: "gore.html" },
    { term: "vidéos gore", file: "gore.html" },
    { term: "gore site", file: "gore.html" },
    { term: "granola", file: "granola.html" },
    { term: "prix granola", file: "granola.html" },
    { term: "faire ses propre granola", file: "granola.html" },
    { term: "gulli", file: "gulli.html" },
    { term: "gulli replay", file: "gulli.html" },
    { term: "gulli max", file: "gulli.html" },
    { term: "israel", file: "israel.html" },
    { term: "pourquoi il y a la guerre avec israel", file: "israel.html" },
    { term: "conflis israel", file: "israel.html" },
    { term: "enceinte jbl", file: "jbl.html" },
    { term: "jbl", file: "jbl.html" },
    { term: "jbl prix enceinte", file: "jbl.html" },
    { term: "kana", file: "kana.html" },
    { term: "manga kana", file: "kana.html" },
    { term: "prochaine sortie kana", file: "kana.html" },
    { term: "linux", file: "linux.html" },
    { term: "gnu linux", file: "linux.html" },
    { term: "est ce que linux est mieux que windows", file: "linux.html" },
    { term: "linux mint", file: "linuxmint.html" },
    { term: "télécharger linux mint", file: "linuxmint.html" },
    { term: "linux mint derniere version", file: "linuxmint.html" },
    { term: "lyreco", file: "lyreco.html" },
    { term: "fourniture de bureau lyreco", file: "lyreco.html" },
    { term: "lyreco papier a4", file: "lyreco.html" },
    { term: "mort", file: "mort.html" },
    { term: "la mort", file: "mort.html" },
    { term: "comment ne pas avoir peur de la mort", file: "mort.html" },
    { term: "naruto", file: "naruto.html" },
    { term: "naruto shipuden", file: "naruto.html" },
    { term: "boruto", file: "naruto.html" },
    { term: "netflix", file: "netflix.html" },
    { term: "netflix abonnement", file: "netflix.html" },
    { term: "augmentation prix netflix", file: "netflix.html" },
    { term: "nginx", file: "nginx.html" },
    { term: "comment installer nginx sur debian", file: "nginx.html" },
    { term: "nginx derniere version", file: "nginx.html" },
    { term: "nodejs", file: "nodejs.html" },
    { term: "télécharger nodejs", file: "nodejs.html" },
    { term: "documentation nodejs", file: "nodejs.html" },
    { term: "palestine", file: "palestine.html" },
    { term: "urgence humanitaire palestine", file: "palestine.html" },
    { term: "quand le conflit en palestine va s'arreter", file: "palestine.html" },
    { term: "pepsi", file: "pepsi.html" },
    { term: "boisson pepsi", file: "pepsi.html" },
    { term: "pepsi prix", file: "pepsi.html" },
    { term: "pessi", file: "pessi.html" },
    { term: "pessi twitter", file: "pessi.html" },
    { term: "pessi raid twitter", file: "pessi.html" },
    { term: "plafond", file: "plafond.html" },
    { term: "faux plafond", file: "plafond.html" },
    { term: "prix plafond", file: "plafond.html" },
    { term: "paris saint germain", file: "PSG.html" },
    { term: "psg", file: "PSG.html" },
    { term: "psg ligue des champion", file: "PSG.html" },
    { term: "rage", file: "rage.html" },
    { term: "maladie de la rage", file: "rage.html" },
    { term: "rage dangeureux annimal", file: "rage.html" },
    { term: "ramadan", file: "ramadan.html" },
    { term: "date du ramadan", file: "ramadan.html" },
    { term: "c'est quoi le ramadan", file: "ramadan.html" },
    { term: "seegore", file: "seegore.html" },
    { term: "goresee", file: "seegore.html" },
    { term: "regarder du gore", file: "seegore.html" },
    { term: "sopalin", file: "sopalin.html" },
    { term: "sopalin essuie tout", file: "sopalin.html" },
    { term: "sopalin lotus", file: "sopalin.html" },
    { term: "verbatim", file: "verbatim.html" },
    { term: "clé usb verbatim", file: "verbatim.html" },
    { term: "cd rw verbatim", file: "verbatim.html" },
    { term: "attentat russie", file: "crocuscityattentat.html" },
    { term: "attentat salle de concert russie", file: "crocuscityattentat.html" },
    { term: "attentat du crocus city en russie", file: "crocuscityattentat.html" },
    { term: "russie attentat salle de concert", file: "crocuscityattentat.html" },
    { term: "crocus city", file: "crocuscityattentat.html" },
    { term: "attentat moscou", file: "crocuscityattentat.html" },
    { term: "bilan attentat russie", file: "crocuscityattentat.html" },
    { term: "visual studio code", file: "visualstudiocode.html" },
    { term: "télécharger visual studio code", file: "visualstudiocode.html" },
    { term: "visual studio", file: "visualstudiocode.html" },
    { term: "yoplait", file: "yoplait.html" },
    { term: "yop", file: "yoplait.html" },
    { term: "yahourt a boire yoplait", file: "yoplait.html" }

  ];

  // Vérification directe de la correspondance exacte
  for (var i = 0; i < searchMappings.length; i++) {
    if (searchTerm === searchMappings[i].term) {
      window.open(searchMappings[i].file);
      return; // Sortir de la fonction si une correspondance exacte est trouvée
    }
  }

  // Création de l'objet Fuse avec les options appropriées
  var fuseOptions = {
    shouldSort: true,
    threshold: 0.4,
    keys: ["term"]
  };
  var fuse = new Fuse(searchMappings, fuseOptions);

  // Recherche floue pour trouver une correspondance proche
  var results = fuse.search(searchTerm);

  // Vérification des résultats trouvés
  if (results.length > 0) {
    var closestMatch = results[0].item;
    window.open(closestMatch.file);
  }
}
